### ISSUE TITLE
Question around the success and updates.

### ISSUE THREAD

**Issue by jacobcarey** [yobro2033/simple-glastonbury-festival-script#1]
Hey,

I've just been looking at your solution for this, and I've not seen many others attempt to poll the post endpoint, it seems like it could be a very efficient method!

Did you have any success with this? And, could you let me know if you made any further updates?

Cheers!

**Comment by yobro2033** [comment]
I've decided not to open-source the code due to the nature of the event.

**Comment by yobro2033** [comment]
Just gonna give you a quick details into this solution, you can do this method and track the response from the website by reading the content, keep it at a certain delay, as soon as different content is displayed, get the cookies from session, that cookies will get you pass queue. You can use any extension on google to import cookies to your current browser

**Comment by jacobcarey** [comment]
Hey, thanks for the follow up! 

Love this solution, I've seen quite a few people building their own scripts, but they're all pretty similar, and this is the first time I've seen someone hitting the _addregistrations_  endpoint directly. I've been building one myself, but keep changing my mind about the implementation, as I worried the website would change, but this method feels like it has potential. I'm thinking I could add something like this, and then load the valid session and launch a browser (selenium or similar) with the session already passed in.  

Did you have any success with it last year, or do you plan to test it in the upcoming sale?

**Comment by yobro2033** [comment]
Yes the website is changing and there are several implementations you need to adapt with, for example the sales page for coach is entirely different than the sales page for general admission and the flow of general sale is also different from the spring sales, you will need to make your script to adapt to all scenarios or it will get stuck somewhere along the way. It's easy to develop script for passing waiting page but I wouldn't give much hope if you don't have enough infos for full flow. I did have success yea but I won't be releasing any of it because it's illegal to use bot to automate ticket purchasing and it would give an unfair advantage to people have access to the script

**Comment by jacobcarey** [comment]
Yep, that is the biggest challenge. I have some knowledge of the flow, but as you said, it's hard to nail it down, as a few changes could throw the whole thing off. Last year, I did try to replay some of the payloads after my page froze, but had no success. 

How did you go about testing this outside of a sales window? 

Fully understand the need to keep it closed, but I appreciate your reply anyway. If you have some time to share any pointers in to testing this and building it out to accompany all scenarios, but would rather keep this away from a public forum, I can share my email and I can delete this thread. 

Thanks again!
